### ISSUE TITLE
Console error README.md doesn't have a .mtea file causing console errors.

### ISSUE THREAD

**Issue by lgomeszanforlin** [ManageXR/mxr-unity-sdk#73]
Upon importing the package our project constantly throws the console error: Asset Packages/com.mxr.unity.sdk/README.md has no meta file, but it's in an immutable folder. The asset will be ignored.

Please generate and include the .meta file for your README file.

**Comment by johnmanagexr** [comment]
Thanks for reporting this @lgomeszanforlin ! @adrenak can you please get this generated?

**Comment by adrenak** [comment]
This was an issue with v1.0.0, later releases don't have this issue. Releases are [here](https://github.com/ManageXR/mxr-unity-sdk/releases/tag/v1.0.13) and installation instructions have been updated.
