### ISSUE TITLE
Incorrect install instructions.

### ISSUE THREAD

**Issue by lgomeszanforlin** [ManageXR/mxr-unity-sdk#74]
The formatting for the scoped dependency is incorrect. It shouldn't include the version number as it'll cause a console error.

This is what is currently written in the documentation:
```
{
   "scopedRegistries": [
      {
            "name": "package.openupm.com",
            "url": "https://package.openupm.com",
            "scopes": [
               "com.mxr.unity.sdk"
            ]
      }
   ],
   "dependencies": {
      "com.mxr.unity.sdk": "1.0.0"
   }
}  
```

This is what we needed to do to make it work:

```
{
   "scopedRegistries": [
      {
            "name": "package.openupm.com",
            "url": "https://package.openupm.com",
            "scopes": [
               "com.mxr.unity.sdk"
            ]
      }
   ],
   "dependencies": {
      "com.mxr.unity.sdk"
   }
}  
```

**Comment by johnmanagexr** [comment]
Thanks for reporting this @lgomeszanforlin ! @adrenak can you please update the README while taking a look at the meta file issue?

**Comment by adrenak** [comment]
@lgomeszanforlin I tried the installation as per readme in an empty project and it worked. 

The dependencies list requires a key (package name) and value (version name) both so your fix should actually cause Unity to say that it's not valid json. To install, `"com.mxr.unity.sdk":"1.0.0"` should be added to the _already existing_ dependencies list in manifest.json.

Regardless, we're now recommending installing the SDK using github tags as it's just a lot more straightforward. See the updated Installation section in readme. The registry at openupm.com also seems to be ignoring our releases post `v1.0.10`, so it's not recommended for use.

**Comment by adrenak** [comment]
Closing as we've started recommending Git tag based installations for now
