### ISSUE TITLE
README file recommends using version 1.0.0, however, the initialization method recommended on the README is not available on v1.0.0

### ISSUE THREAD

**Issue by lgomeszanforlin** [ManageXR/mxr-unity-sdk#75]
The async init mentioned on the package documentation seem to only be available on higher versions of the SDK even though the documentation recommends v 1.0.0

It worked on 1.0.10 for me.

**Comment by adrenak** [comment]
Hi @lgomeszanforlin thanks for reporting and sorry for the confusion! I checked and async initialization was added [in version v1.0.5](https://github.com/ManageXR/mxr-unity-sdk/releases/tag/v1.0.5)

The documentation does use v1.0.0 in the installation examples, but [says that the latest version is recommended](https://github.com/ManageXR/mxr-unity-sdk/blob/174b254fb117756af5d9dd42bf11148d32f32933/README.md?plain=1#L49):
> Note: Change 1.0.0 to the SDK version you wish to use. Latest recommended.

There's a change going out to make that note more visible. 

We're yet to have version specific documentation, so README currently reflects the latest release.
